# Language setting
language: python

runtime:
  nodePool: custom__x86_64__Ubuntu_16_04
  
# Version number
python:
  - 2.7

build:
   pre_ci_boot:
    image_name: drydock/w16
    image_tag: master
    pull: true
    
  ci:
    - echo "hello"

resources:

  - name: version-resource1win
    type: version
    seed:
      versionName: "0.0.1-beta"

  - name: repo1win
    type: gitRepo
    integration: github
    pointer:
      sourceName: Varsha-Arun/sample_pipelines
      branch: master
      
  - name: notify-slack1win
    type: notification
    pointer:
      method: email
      recipients: 
       # - deepika@shippable.com
        - varsha@shippable.com
      
jobs:
  - name: simplerunsh1win
    type: runSh
    runtime:
      nodePool: custom__x86_64__Ubuntu_16_04
    steps:
      - IN: repo
      - TASK:
        - script: ls
       # - script: sleep 3m
        #- script: ./GET/infra-repo/infra-repo/provision.sh
    always:
      - script: echo "This works on_always"
      - NOTIFY: notify-slack1
      
triggers:
   - name: triggersp1win
     type: trigger
     version:
       counter: 8
       
   - name: triggersp2win
     type: trigger
     version:
       counter: 7
       
   - name: triggersp3win
     type: trigger
     version:
       counter: 1
